### ISSUE TITLE
Two small problems in Step 4

### ISSUE THREAD

**Issue by li1553770945** [tufts-ml/aced-hmm-hospitalized-patient-trajectory-model#2]
Hello! I have  ran your sample workflow, but it seems like to have two small problems in Step 4.
First,it is `aced_hmm.ABC_test_metric`,not `aced_hmm.abc_test_metric`,second it should be ` --config_path` instead of ` --config_file`.
It should be:
`$ python -m aced_hmm.ABC_test_metrics --input_dir [results/US/MA-20201111-20210111-20210211] \
                                      --output_dir [results/US/MA-20201111-20210111-20210211] \
                                      --output_template [metrics_after_abc] \
                                      --config_path [results/US/MA-20201111-20210111-20210211/config_after_abc.json] \
                                      --true_stats [datasets/US/MA-20201111-20210111-20210211/daily_counts.csv] \
                                      --input_summaries_template [summary_after_abc_] \
                                      --coverages [2.5_97.5,10_90,25_75] \
                                      --comma_sep_expected_columns [n_InGeneralWard,n_OffVentInICU,n_OnVentInICU,n_InICU,n_occupied_beds,n_TERMINAL,n_TERMINAL_5daysSmoothed]
`.
Thanks!

**Comment by michaelchughes** [comment]
Thanks very much @li1553770945. I have just fixed these two typos in our main repo. 

Really appreciate the feedback.

If you have further questions or issues, please do let us know.

Best,
Mike Hughes
